### ISSUE TITLE
I cannot make it run

### ISSUE THREAD

**Issue by ghost** [shyamjos/Fire_Bot#1]
Hi there

I'm trying to run your Fire_Bot without success. I execute:
`$ python2 firebot.py`
And I get:

```
Traceback (most recent call last):
  File "firebot.py", line 36, in <module>
    fire_bot.serve_forever() 
  File "/usr/lib/python2.7/site-packages/jabberbot.py", line 715, in serve_forever
    conn = self.connect()
  File "/usr/lib/python2.7/site-packages/jabberbot.py", line 208, in connect
    conres = conn.connect()
  File "/usr/lib/python2.7/site-packages/xmpp/client.py", line 205, in connect
    while not self.TLS.starttls and self.Process(1): pass
  File "/usr/lib/python2.7/site-packages/xmpp/dispatcher.py", line 303, in dispatch
    handler['func'](session,stanza)
  File "/usr/lib/python2.7/site-packages/xmpp/transports.py", line 337, in StartTLSHandler
    self._startSSL()
  File "/usr/lib/python2.7/site-packages/xmpp/transports.py", line 316, in _startSSL
    tcpsock._sslIssuer = tcpsock._sslObj.issuer()
AttributeError: '_ssl._SSLSocket' object has no attribute 'issuer'
```

Any idea?

**Comment by shyamjos** [comment]
there is a bug in xmppy lib. Here is the patch:
https://raw.githubusercontent.com/freebsd/freebsd-ports/master/net-im/py-xmpppy/files/patch-xmpp-transports.py

**Comment by ghost** [comment]
Thank you! I'll take a look.
